[versions]
kotlin = "2.2.21"
kotlinxSerialization = "1.8.1"
kotlinx-coroutines = "1.9.0"

fastutil = "8.5.18"

lwjgl = "3.3.6"
jarOptimizer = "1.2.2"

[plugins]
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jarOptimizer = { id = "dev.luna5ama.jar-optimizer", version.ref = "jarOptimizer" }

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }

[bundles]
kotlinEcosystem = ["kotlin-reflect", "kotlinx-coroutines"]
