[versions]
kotlin = "2.3.0"
kotlinxSerialization = "1.9.0"
kotlinx-coroutines = "1.10.2"

fastutil = "8.5.18"

lwjgl = "3.3.6"
jarOptimizer = "1.2.2"

[plugins]
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jarOptimizer = { id = "dev.luna5ama.jar-optimizer", version.ref = "jarOptimizer" }

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
letsPlot = { module = "org.jetbrains.lets-plot:lets-plot-kotlin-jvm", version = "4.4.1" }
simpleLogger = { module = "org.slf4j:slf4j-simple", version = "2.0.17" }

fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }

[bundles]
kotlinEcosystem = ["kotlin-reflect", "kotlinx-coroutines", "letsPlot"]
